CREATE TABLE history_empy1_dev.history_employee(
SNAPSHOTDATE DATE NOT NULL
,EMPLID STRING
,EMPL_CLASS	STRING
,POSITION_NBR	INTEGER
,POSITION_DESCRIPTION	STRING
,DEPTID	STRING
,DIRECOTRATE_DESCRIPTION	STRING
,DEPARTMENT_DESCRIPTION	STRING
,ACCT_CD	STRING
,LOCATION	STRING
,ORG_LEVEL INT64	
,L1_EMPLID	STRING
,L1_NAME	STRING
,L1_POSITION_NBR	STRING
,L1_POSITION_NAME	STRING
,L2_EMPLID	STRING
,L2_NAME	STRING
,L2_POSITION_NBR	STRING
,L2_POSITION_NAME	STRING
,L3_EMPLID	STRING
,L3_NAME	STRING
,L3_POSITION_NBR	STRING
,L3_POSITION_NAME	STRING
,LEVEL	INTEGER
,HIRE_DATE	DATE
,REHIRE_DT DATE	
,SERVICE_DT	DATE
,REAL_SERVICE_DATE	DATE
,CTRY_CDE STRING,
,STE_CDE STRING ,
,LAST_UPDATED	TIMESTAMP ) ;

